### ISSUE TITLE
Multiple mapping to same class error

### ISSUE THREAD

**Issue by cedricfortin** [txusballesteros/android-transformer#8]
I've got a problem mapping multiple classes to the same class when they belong to the same package. For example:
Class A map to Class C
Class B map to Class C
Class A and B are in the same package.

The problems seems to be with the generated Transformer class (which is created by package) and that add 2 entries with the same key:
<code>
addMapper("com.example.model.C", new com.example.viewmodel.A());
addMapper("com.example.model.C", new com.example.viewmodel.B());
</code>

As a result when I try to transform class C to class A it works.
But when I try to transform class C to class B it give me a cast error: class A connot be cast to class B.

**Comment by tonilopezmr** [comment]
So class A and class B are identical ?

**Comment by cedricfortin** [comment]
No, class A and B are differents as I use them in differents views and contains differents properties of class C

**Comment by txusballesteros** [comment]
IMHO, you have a bad smell in your approach, for me, you should not mix different objects with the same middle object, I mean, if you do that you're breaking you separation between objects and you're coupling those.
